//! Terminal presentation and explicitly user-configured local programs.
use std::io::{IsTerminal, Write};
use std::process::Command;

use unicode_segmentation::UnicodeSegmentation;
use unicode_width::UnicodeWidthStr;

use crate::output::sanitize_terminal_text;

pub(crate) const MAX_DRAFT_BYTES: u64 = 64 * 1024;

pub(crate) fn width(value: &str) -> usize {
    UnicodeWidthStr::width(value)
}

pub(crate) fn truncate(value: &str, columns: usize) -> String {
    let value = sanitize_terminal_text(value);
    if width(&value) <= columns {
        return value;
    }
    if columns == 0 {
        return String::new();
    }
    let mut result = String::new();
    for grapheme in value.graphemes(true) {
        if width(&result) + width(grapheme) > columns - 1 {
            break;
        }
        result.push_str(grapheme);
    }
    result.push('…');
    result
}

/// Preserve paragraph boundaries and never split a grapheme cluster.
pub(crate) fn wrap(value: &str, columns: usize) -> Vec<String> {
    let columns = columns.max(1);
    let value = sanitize_terminal_text(value);
    let mut result = Vec::new();
    for paragraph in value.split('\n') {
        let mut line = String::new();
        for word in paragraph.split_whitespace() {
            if !line.is_empty() && width(&line) + 1 + width(word) <= columns {
                line.push(' ');
                line.push_str(word);
                continue;
            }
            if !line.is_empty() {
                result.push(std::mem::take(&mut line));
            }
            for grapheme in word.graphemes(true) {
                if !line.is_empty() && width(&line) + width(grapheme) > columns {
                    result.push(std::mem::take(&mut line));
                }
                line.push_str(grapheme);
            }
        }
        result.push(line);
    }
    result
}

/// Strip only the SGR sequences generated by our own theme. Untrusted controls
/// have already been neutralized before they reach a themed line.
pub(crate) fn strip_styles(value: &str) -> String {
    let mut rest = value;
    let mut output = String::new();
    while let Some(index) = rest.find("\u{1b}[") {
        output.push_str(&rest[..index]);
        rest = &rest[index..];
        if let Some(end) = rest.find('m').filter(|end| {
            rest[2..*end]
                .chars()
                .all(|c| c.is_ascii_digit() || matches!(c, ';' | ':'))
        }) {
            rest = &rest[end + 1..];
        } else {
            output.push('\u{1b}');
            rest = &rest[1..];
        }
    }
    output.push_str(rest);
    output
}

/// Wrap code without collapsing indentation or repeated spaces.
pub(crate) fn wrap_verbatim(value: &str, columns: usize) -> Vec<String> {
    let columns = columns.max(1);
    let mut lines = Vec::new();
    for source in sanitize_terminal_text(value).split('\n') {
        let mut line = String::new();
        for grapheme in source.graphemes(true) {
            if !line.is_empty() && width(&line) + width(grapheme) > columns {
                lines.push(std::mem::take(&mut line));
            }
            line.push_str(grapheme);
        }
        lines.push(line);
    }
    lines
}

pub(crate) fn format_cost(microusd: Option<u64>) -> String {
    microusd.map_or_else(
        || "— (no cost reported)".to_owned(),
        |v| format!("${}.{:06}", v / 1_000_000, v % 1_000_000),
    )
}

/// Parse a program and argv, never a shell expression. Only user configuration
/// calls this; model strings cannot choose a host program.
pub(crate) fn program(value: &str) -> Result<Command, String> {
    let words = shell_words::split(value).map_err(|error| error.to_string())?;
    let Some((executable, args)) = words.split_first() else {
        return Err("set VISUAL or EDITOR to an executable, for example `nvim`".to_owned());
    };
    if executable.is_empty() {
        return Err("the configured executable is empty".to_owned());
    }
    let mut command = Command::new(executable);
    command.args(args);
    Ok(command)
}

pub(crate) fn edit_draft(draft: &str, workspace: &std::path::Path) -> Result<String, String> {
    let editor = std::env::var("VISUAL").ok().filter(|s| !s.trim().is_empty())
        .or_else(|| std::env::var("EDITOR").ok().filter(|s| !s.trim().is_empty()))
        .ok_or_else(|| "Set VISUAL or EDITOR first, then use /editor. Alt+Enter and Ctrl+J also insert newlines.".to_owned())?;
    let mut command = program(&editor)?;
    command.current_dir(workspace);
    let mut file = tempfile::Builder::new()
        .prefix("pactrail-draft-")
        .suffix(".md")
        .tempfile()
        .map_err(|e| e.to_string())?;
    file.write_all(draft.as_bytes())
        .and_then(|()| file.flush())
        .map_err(|e| e.to_string())?;
    let status = command
        .arg(file.path())
        .status()
        .map_err(|e| format!("could not launch editor: {e}"))?;
    if !status.success() {
        return Err(format!(
            "editor exited with {status}; the previous draft is unchanged"
        ));
    }
    read_draft(file.path())
}

pub(crate) fn read_draft(path: &std::path::Path) -> Result<String, String> {
    use std::io::Read;
    let metadata = std::fs::metadata(path).map_err(|e| e.to_string())?;
    if !metadata.is_file() {
        return Err("task input must be a regular file".to_owned());
    }
    if metadata.len() > MAX_DRAFT_BYTES {
        return Err("task file exceeds 64 KiB".to_owned());
    }
    let file = std::fs::File::open(path).map_err(|e| e.to_string())?;
    let mut bytes = Vec::new();
    file.take(MAX_DRAFT_BYTES + 1)
        .read_to_end(&mut bytes)
        .map_err(|e| e.to_string())?;
    if bytes.len() as u64 > MAX_DRAFT_BYTES {
        return Err("task file exceeds 64 KiB".to_owned());
    }
    String::from_utf8(bytes).map_err(|_| "task file must be UTF-8".to_owned())
}

/// True only when a pager displayed the output successfully. A failed launch
/// returns an explanation so the caller can fall back to ordinary scrollback.
pub(crate) fn page(value: &str, enabled: bool) -> Result<bool, String> {
    if !enabled
        || !std::io::stdout().is_terminal()
        || std::env::var("TERM").is_ok_and(|s| s == "dumb")
    {
        return Ok(false);
    }
    let rows =
        terminal_size::terminal_size().map_or(24, |(_, terminal_size::Height(h))| usize::from(h));
    if value.lines().count() <= rows.saturating_sub(4) {
        return Ok(false);
    }
    let configured = std::env::var("PAGER").unwrap_or_else(|_| "less -FRX".to_owned());
    if configured.trim().is_empty() {
        return Ok(false);
    }
    let mut command = program(&configured)?;
    // Prevent less from running external preprocessors or shell escapes.
    if std::path::Path::new(command.get_program())
        .file_stem()
        .is_some_and(|s| s == "less")
    {
        command
            .env("LESSSECURE", "1")
            .env_remove("LESSOPEN")
            .env_remove("LESSCLOSE");
    }
    let mut file = tempfile::Builder::new()
        .prefix("pactrail-review-")
        .tempfile()
        .map_err(|e| e.to_string())?;
    file.write_all(value.as_bytes())
        .and_then(|()| file.flush())
        .map_err(|e| e.to_string())?;
    let status = command
        .arg(file.path())
        .status()
        .map_err(|e| format!("pager unavailable ({e}); showing the full output here"))?;
    if !status.success() {
        return Err(format!(
            "pager exited with {status}; showing the full output here"
        ));
    }
    Ok(true)
}

#[derive(Debug, Default, PartialEq, Eq)]
pub(crate) struct ReviewCautions {
    pub unverified: bool,
    pub failed: usize,
    pub stale: bool,
}

pub(crate) fn review_cautions(
    receipt: &pactrail_core::ChangeReceipt,
    events: &[pactrail_core::EventEnvelope],
) -> ReviewCautions {
    use pactrail_core::{EvidenceGrade, EvidenceStatus, RunEvent};
    let latest_write = events
        .iter()
        .filter_map(|e| match &e.event {
            RunEvent::ActionCompleted(action)
                if action.observed_effects.iter().any(|effect| {
                    effect.starts_with("fs.changed:") || effect.starts_with("fs.write:")
                }) =>
            {
                Some(e.sequence)
            }
            _ => None,
        })
        .max();
    let latest_evidence = events
        .iter()
        .filter_map(|e| matches!(e.event, RunEvent::EvidenceRecorded(_)).then_some(e.sequence))
        .max();
    ReviewCautions {
        unverified: !receipt
            .evidence
            .iter()
            .any(|e| e.grade == EvidenceGrade::Deterministic && e.status == EvidenceStatus::Passed),
        failed: receipt
            .evidence
            .iter()
            .filter(|e| e.status == EvidenceStatus::Failed)
            .count(),
        stale: latest_write
            .zip(latest_evidence)
            .is_some_and(|(write, evidence)| write > evidence),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn cell_width_preserves_unicode_and_paragraphs() {
        let lines = wrap("路径路径路径 e\u{301} 😀\n\nnext", 8);
        assert!(lines.iter().all(|s| width(s) <= 8));
        assert!(lines.contains(&String::new()));
        assert!(lines.join("").contains("e\u{301}"));
        assert_eq!(truncate("路径路径", 5), "路径…");
        assert_eq!(truncate("e\u{301}abc", 2), "e\u{301}…");
    }
    #[test]
    fn configured_program_does_not_execute_shell_syntax() {
        let command = program("'my editor' --wait 'a b' '$(echo secret)' ;")
            .unwrap_or_else(|e| unreachable!("{e}"));
        assert_eq!(command.get_program(), "my editor");
        assert_eq!(
            command.get_args().collect::<Vec<_>>(),
            ["--wait", "a b", "$(echo secret)", ";"]
        );
        assert!(program("'unfinished").is_err());
        assert!(program("").is_err());
    }
    #[test]
    fn code_spacing_and_absent_cost_are_preserved() {
        assert_eq!(wrap_verbatim("  a  b", 4).join(""), "  a  b");
        assert_eq!(format_cost(None), "— (no cost reported)");
        assert_eq!(format_cost(Some(0)), "$0.000000");
        assert_eq!(format_cost(Some(1)), "$0.000001");
    }
    #[test]
    fn task_files_are_bounded_and_utf8() {
        let dir = tempfile::tempdir().unwrap_or_else(|e| unreachable!("{e}"));
        let p = dir.path().join("task.md");
        std::fs::write(
            &p,
            vec![b'a'; usize::try_from(MAX_DRAFT_BYTES).unwrap_or(usize::MAX - 1) + 1],
        )
        .unwrap_or_else(|e| unreachable!("{e}"));
        assert!(read_draft(&p).is_err());
        std::fs::write(&p, [255]).unwrap_or_else(|e| unreachable!("{e}"));
        assert!(read_draft(&p).is_err());
    }
}
